### ISSUE TITLE
程序好像处理不了带有名字带有&的zipmod

### ISSUE THREAD

**Issue by hainiya** [Laa-al/SideloaderModpackUpdater#1]
检查更新不能识别本地名字带有&的mod还是提示要跟新，下载时也是立刻就下载失败

**Comment by hainiya** [comment]
而且有几个mod也是这样，只不过能正常下载，但不能检查更新排除，这些都是1G多的大mod

**Comment by Laa-al** [comment]
> 检查更新不能识别本地名字带有&的mod还是提示要跟新，下载时也是立刻就下载失败

这个问题是因为爬虫为了保证正确的xml格式把&全替换掉了，我想想有什么办法解决，或者我只将几个特定的转义字符串替换试一下。

> 而且有几个mod也是这样，只不过能正常下载，但不能检查更新排除，这些都是1G多的大mod

这个就是我说的不能确保检查到的地方，因为数据是完全从网站上爬到的，所以文件更新对比也会有误差。

**Comment by Laa-al** [comment]
我在master分支中更新了第一个问题，第二个问题我暂时应该解决不了。
更新的程序合并到了v0.0.3版本中。
